version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - dummy_service
      - process_dicom
      - vascular_segmentation
    networks:
      - app-network
    volumes:
      - ~/dicom:/dicom
    container_name: server

  dummy_service:
    build: ./services/dummy_service
    ports:
      - "5001:5001"
    networks:
      - app-network
    container_name: dummy_service

  process_dicom:
    build: ./services/process_dicom
    ports:
      - "5002:5002"
    networks:
      - app-network
    volumes:
      - ~/dicom:/dicom
    container_name: process_dicom

  vascular_segmentation:
    build: ./services/vascular_segmentation
    ports:
      - "5003:5003"
    networks:
      - app-network
    volumes:
      - ~/dicom:/dicom
    container_name: vascular_segmentation
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - nnUNet_compile=F
    runtime: nvidia

networks:
  app-network:
    driver: bridge



